#!============================ << PUBSPEC.YAML >> =================#


name: fly_vihanga 
description: "TRAVEL AND TRANSPORT APP"

publish_to: "none"
version: 1.0.0+1

# FLUTTER -V: 3.16.9 
environment:
  sdk: ">=3.2.3 <4.0.0"

#============================= PACKAGES ==========================#

dependencies:
  flutter:
    sdk: flutter
#*========================= UTILITY PACKAGES =====================#

  http:
  intl:
  logger:
  url_launcher: 
  cached_network_image:
  liquid_swipe:
  smooth_page_indicator: 






#*========================= PRODUCT SPECIFIC PACKAGES ============#
  iconsax: 
  flutter_native_splash: 






#*========================= ICONS PACKAGES =====================#
  cupertino_icons: ^1.0.2

#*========================= STATE MANAGEMENT ===================#

  get:
  get_storage: 
#*==========================UI Needs=============================#

  dotted_line: 








#============================= DEV-PACKAGES ======================#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

#============================= lOCAL ASSETS ======================#

  assets:
    - assets/IMAGES/ON_BOARDING/
    - assets/IMAGES/WELCOME/
    - assets/GIFS/
    - shorebird.yaml
  #   - assets/SVGS
  #   - assets/VIDEOS
  #   - assets/ICONS

#============================= lOCAL FONTS ======================#
  fonts:
    - family: IvyMode
      fonts:
        - asset: assets/FONTS/IVYMODE/IvyMode-Thin.ttf
          weight: 100
        - asset: assets/FONTS/IVYMODE/IvyMode-Light.ttf   
          weight: 300
        - asset: assets/FONTS/IVYMODE/IvyMode-Regular.ttf
          weight: 600
        - asset: assets/FONTS/IVYMODE/IvyMode-SemiBold.ttf
          weight: 700
        - asset: assets/FONTS/IVYMODE/IvyMode-Bold.ttf
          weight: 900
    - family: Nunito
      fonts:
        - asset: assets/FONTS/NUNITO/Nunito-MediumItalic.ttf
          style: italic
        - asset: assets/FONTS/NUNITO/Nunito-Light.ttf
          weight: 300
        - asset: assets/FONTS/NUNITO/Nunito-Light.ttf
          weight: 400
        - asset: assets/FONTS/NUNITO/Nunito-Regular.ttf
          weight: 500
        - asset: assets/FONTS/NUNITO/Nunito-Medium.ttf
          weight: 600
        - asset: assets/FONTS/NUNITO/Nunito-SemiBold.ttf
          weight: 700
        - asset: assets/FONTS/NUNITO/Nunito-Bold.ttf
          weight: 800
        - asset: assets/FONTS/NUNITO/Nunito-ExtraBold.ttf
          weight: 900



#!============================ << END OF PUBSPEC.YAML >> =========#